hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "ea430db88d8f190a053e4f3c662d2a59b6a7508778525034f2b20037ee074aec"
metafile = true

[[files]]
file = "mods/adorable-hamster-pets.pw.toml"
hash = "11a135546ea893de4079cd81b56ff97303e95e2b3a6ffd47c54961ff0ccba79c"
metafile = true

[[files]]
file = "mods/advanced-netherite.pw.toml"
hash = "f61033f5acde76e2405e9549ff54ccdf4d3dc24a9caca015720523f02ee91033"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "7b9bcc299b6587626d256c571fc122e6147d8d760cb7056d537c88cce5d993f9"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
hash = "d48e943c59dd7c5c0c20b80afd23e18e05385ed79b37e80238f949ec0f5e8d9c"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "064b0019e4f545599e5af2a4f74f11777086fce18e68f0b93dd77136ce7c0193"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "71dc04da11ad8f4a5d88db5505132a654ce033f05dc2fa4bb7aa28a42762086f"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
hash = "724353a7730f54b29378ba8e374c78372c8a8f072e578b5758b11fc150f470b7"
metafile = true

[[files]]
file = "mods/better-ping-display-fabric.pw.toml"
hash = "8f54b2270c2d87b56a73b4355305cc4a4dd277330cad97d137b98073ec0d8e83"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "a1e024094c28068c99a6da1c5867cbd4e66a315718039659bfa533a138762d9e"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "a2de85ebe9629568398185b5b9554bcc0c54e322b214d78368485a6074a66279"
metafile = true

[[files]]
file = "mods/botarium.pw.toml"
hash = "2f57caef93731338be19b1e14065978eb3e14dbfc0c1f9699dfcc2f201e2c23b"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "1173755b093b4f9a8aca00520d87bc35178fe19c54e59debe5c48d0c9063b91c"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "58d6861337626edf09635b6bc0bc45f49286c2517a234cb50baee9a23c538fc6"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "15385164e2cd07cce7493a10d6d87df5c7bce587a866613126be3b54b6b28fc7"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "b4fdf52d53ab71bf73282c5168e9526b6024740d82388d604d6947394e3c7f7f"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e81c635602878f92af9a9c11b92481b25c7aaf3f68cd015dabf5f67201886401"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "429284603e4c5ca44777cb4ce2455477fcc1eee4dc9a4ae2f759c4895bf332e7"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "5265e90f91a651c018b78641d08442da55c060ce07a020afdf86bb79d12bbe8d"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "af83eb1ea0f7a36e4424248c744c1cbebb5045d361e843b873d4d89bf65ad8ad"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "5944ed5a779d142aea9ccd8c466a20fa3d9233a29f2be1e5ae54fc15f5edd57e"
metafile = true

[[files]]
file = "mods/estrogen.pw.toml"
hash = "18b0d44213fd3c7e22748e4ad775e6ce5cf243f9b38294130a826c845ae913c4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "fff1e00559f13c092b17fa83804279cf70191d7a99a4a98a4eb6bb30ac9a78db"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "e09385ac1a1c0900b8fa619290eb0f0539949ebbc59f7604a7699485784ccc85"
metafile = true

[[files]]
file = "mods/female-gender.pw.toml"
hash = "e8b80e4eb7ccd9817a18e17fad1187cf27ab8f68a20aa73338be243785add2bc"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "adea09f1e1b05da68cf7407992a9391b15985acf5465a888e54ae076dbd543ab"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "26aabc12649a729a2d5c593fd70ed50933a9fe9c7d16d2bdffa44a2165aa59e1"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "493ed95320ee3cc9c2def86b9d0971c2ca4bb4215921c2a11208bee77d5dbfb5"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "f6629a3c5e023a96cb5d78d66e93b47245996c46a079921b3f6a6094209dc1b0"
metafile = true

[[files]]
file = "mods/immersive-ui.pw.toml"
hash = "71ddcef1fbd1b128a705ce8f9a57e8aeda4421f08c47241484d08bd264cb7c98"
metafile = true

[[files]]
file = "mods/immortal-pets.pw.toml"
hash = "d70e79320fe371c939334769202cc5b403c35609b33558483fbcda7b5737b9f5"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
hash = "cc5ce2c69f275f245fccbb9f673f5b6711175034bdf41f48cfb672e652ea984b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b023a335aa5ebb14048587cfef85b374c023518a1db303eb24f1175530ab0085"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "9495bb2388d7fa5ccf6b33b485f75c7ed15f8a59956406a92ad427e8504980e8"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "d6be91dc0a2aca23ee640818d8a8295c85ddb2db6e0413669ecac9600b01eef0"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "8508e46b7e272d79dc6b3cc0149f9fd132c701369bcb2abb5c35da3ed92b27fb"
metafile = true

[[files]]
file = "mods/lets-do-vinery.pw.toml"
hash = "419bd839d19392cc602591a1bd9975e02e4f946f93f161fa793865530628af63"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
hash = "cc298019c2d3a47a97e72363b942fe408e5ecb7ff476fe08155793f2f1578317"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "bc91fa90e9f26f3ff3690c1a508647a162cd63dc36d815b8af0d6f5e01e5ecbf"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ede2f61d6b592f44294fa8790c2f050729c487aa86aba09034f2ef30d45e0e93"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "200d34b575b506ab0503f7856cdcd4cc38030c27e0749e36f6bbe62cbeb16cec"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "9ce6efc7149cdae2deb751b4ebf2d220700cc1b204e7a1d026275203387f106b"
metafile = true

[[files]]
file = "mods/noend.pw.toml"
hash = "b190b34b2b5b74238fb5015dada4bea38401896ebc9abfec62fbaa979b0fb27b"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "89ed99a0798a5e1300434359762c968536593279493f68b321a565fb1343f75c"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "8f6b83625e06798510048832addd6b1bf709b5d5e7dba438d002fe2dc110981b"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "eff75aaa788bf041f3767fb0115a0d9fbfc9d75d2464860c5b47674dfc79178e"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "3c2fe6485d980a094a5094263d9d54dd59bd4cfd37439109be561894342a82f8"
metafile = true

[[files]]
file = "mods/platform.pw.toml"
hash = "5beb6ef32d80ab0550baad15f1fd78f2c6168fcce4a18e14e23c47a1cc8ed099"
metafile = true

[[files]]
file = "mods/pneumono_core.pw.toml"
hash = "a82f238f742cc233dd908c78ae50437bc3012950b4bb0afa7b570faed27c49fd"
metafile = true

[[files]]
file = "mods/pneumono_gravestones.pw.toml"
hash = "6e0e1e035d3662088d59d8bb9cbb25217fd9d954ab004a7d463f6ef6fa644db8"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8293786ca23e23e7dd04d60d666f34145a00229a5959f7a1962995654cacdf1f"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "a1eff7b33a54586b6989c7bfd89992f9d315f1c656b7596649d9af7017c6af7b"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "3f9e020fb15e1c2ede36d50b40c72d536f6de3f817bd703d26805a747175c8bc"
metafile = true

[[files]]
file = "mods/rottencreatures.pw.toml"
hash = "86dd30664de6dd1d53e9ecec18ea7c3feb0b8b1e4862616af6fa5207a528c694"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "830270b8e5a34f5621720ae09c4cf716a65d8003a30d585c8b817aba1fde9ac8"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "fae2bc6c282159f6a2e55e22d19241c625a9795dddbe8bd0f0b501c8aa709be1"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "b1dd6ac8ea2df432d01c0c2f93634f96d5e7b15439c41f0d8b050bca8714bace"
metafile = true

[[files]]
file = "mods/snowy-spirit.pw.toml"
hash = "c7f87fa4a0fb66266880aebfd5c1afe13e6532037cdbfd6c29ed28021977bde5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
hash = "0238d3e484f1829aaabb3b2482e528e192f3124fad89d81f43d7b60406e17d71"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
hash = "6e5a8f947f77a0a9cf18347edd01a08fc725c2ecaa10cf61e6b429a54e50a463"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "5267cd0ff94e2695e70720e94c8940045a6a7371c89c3adcad48660b303698dd"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "a7cff3a04db0673f1a5a9513015c83ae0a6bee936a8c6a1ed08ae12e0e3ba2f6"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
hash = "df3dab0a368d87080cf735e0c0a253962e47a9ed6b40054736b52e375a471e2d"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3135bb6ec401e951d248de79dbdf40608e362e64b89fe9e7d2e74399f3b49375"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "b3ae602303fd717bff2344bfb89aa427e2b4a1ab5fffdcc25183b22102c492df"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "df71b5d7427e9a508e9f298b5cdec84aa8c4fcb584beb0d16d86efb9d47b3bcd"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "ffdb79f5bc29f990e5889f5d159a043c7046b8cd8d79f17f54b44d7ccc2b242a"
metafile = true

[[files]]
file = "mods/visual-workbench.pw.toml"
hash = "a9b241cbbff036293ceb73c9fac0f58c2b1d60cefb2aed0212fc936556a16df8"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
hash = "021d42f729c7fba0ddca97369323325002ecb8437e2948d82478e682bb340e58"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "982ddeeb761a8e001ed2b0487b916bb08d012666d369c7e6aeb0e5d950b6e99f"
metafile = true

[[files]]
file = "mods/winterly.pw.toml"
hash = "65dd82d571f8893ea5bb1410e7d9e7480a4014e21e2a907c2c44212bc133fdd1"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "fd725a2383164ee2866a41635b0a8baf4cc1506d33df1ce1cc1455ab98a32e01"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "7598f0435251f845fdf85c8ed2ac612b2d0404e0ee73a1fcdebaf4eb6c95296d"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "95940b5fc72e8df82ab3adb72b43d10a37e6d926fbb37c405c9fe50bda27a991"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "0958d9f10d0e8fb282b8e684b05b37b29aca826d48deeec3e44171857c99aca5"
metafile = true

[[files]]
file = "mods/yungs-better-mineshafts.pw.toml"
hash = "cf708ff146f867df2153b3f27482e80769c7032b10037e4a752d31fbb5668eaf"
metafile = true

[[files]]
file = "mods/yungs-bridges.pw.toml"
hash = "7e89ac9ea56f87a811a289d474b8ab4fe46d7a235b4c6ef4767e5099967d656e"
metafile = true

[[files]]
file = "mods/yungs-extras.pw.toml"
hash = "d201155cab7c2a2cf940d91f240be769ac12046c2fc6a0774e225a8e51423ed0"
metafile = true
