name = "Polar Pigeons Modpack"
author = "eiiko6"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ac3c8c4928feaac64910655e0f82a8642671fd1ce9f578ebb58dd5117d83c51"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
