name = "Polar Pigeons Modpack"
author = "eiiko6"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3ebf5b419db7392e8630d86b26d7969fe09a4bd5b4b1e8f80f901f075048ca1"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
