name = "Polar Pigeons Modpack"
author = "eiiko6"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ccf3597c96e49a9da3899e5baabdeb0ec26f029fd7b6283987d2ca7299a6f762"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
