name = "polar-pigeons-modpack"
author = "eiiko6"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "315816b0016872175a1c4c98c61726a2fc14c9efcdf1bd7dfa4526fe75194f4f"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
