name = "Polar Pigeons Modpack"
author = "eiiko6"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97ef6f3cc9e4154af59c7f1de977b327c7c9491484e5fcd8ead971a1452988db"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
