name = "Polar Pigeons Modpack"
author = "eiiko6"
version = "0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8c4c4a595a85465cf855801e62ba691dfa067a5235ea291a4917b9f7ef6edc2"

[versions]
fabric = "0.18.1"
minecraft = "1.20.1"
